set(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_C_COMPILER i686-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER i686-w64-mingw32-g++)

SET(CMAKE_FIND_ROOT_PATH  /usr/i686-w64-mingw32)

set(MINGW_FROM_UNIX 1)

#set(CROSS_COMPILE_TOOLCHAIN_PREFIX "i686-w64-mingw32")
#
## here is the target environment located
#
#set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
#set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

